[tools]
rojo = "rojo-rbx/rojo@7.6.1"
selene = "kampfkarren/selene@0.29.0"
stylua = "johnnymorganz/stylua@2.3.1"
wally = "upliftgames/wally@0.3.2"
wally-package-types = "JohnnyMorganz/wally-package-types@1.6.2"
